### ISSUE TITLE
多级表头的第一列总是跑到最后一列

### ISSUE THREAD

**Issue by yang5355** [StrivingRabbit/zvue#2]
如题，多级表头的columnConfig数据日期是第一列，运行时总是会跑到最后一列

**Comment by StrivingRabbit** [comment]
查看是否是使用了fixed

**Comment by yang5355** [comment]
哦，确实是使用了fixed固定列。还有一个小小bug，如果不设置fixed同时又开启索引（showIndex: true），即索引与第一列之间没有边框线条
![issue](https://user-images.githubusercontent.com/59274878/103121702-58a3f900-46b8-11eb-9288-a6e6cb68d693.png)

**Comment by StrivingRabbit** [comment]
好的，这个问题我后面瞅瞅
